# Generated by Django 4.2.4 on 2023-08-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('data_lancamento', models.IntegerField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
