# Generated by Django 4.2.4 on 2023-09-15 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_livroinventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LivroInventory',
        ),
    ]
