# Generated by Django 4.2.4 on 2023-09-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0006_delete_livroinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivroInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_livros', models.IntegerField()),
                ('valor_livros', models.FloatField()),
                ('registro_criado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-registro_criado'],
            },
        ),
    ]
